name: PR
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Generate layout.json and update manifest.json
        run: python build.py
          
      - uses: actions/upload-artifact@v2
        with:
          name: A32NX
          path: ./Flight-Sim-Model-Matching-Models/